_wandb:
    value:
        cli_version: 0.23.0
        e:
            6wrnqflqh28g5jz6s9on0o2p02xzc0a1:
                args:
                    - --task=b1z1
                    - --exptid=7
                    - --run_name=b1z1_fd_fixied
                    - --headless
                codePath: legged_gym/legged_gym/scripts/train.py
                codePathLocal: legged_gym/legged_gym/scripts/train.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "916243312640"
                        used: "430869127168"
                email: 3155853275@qq.com
                executable: /home/adam/anaconda3/envs/DWBC/bin/python
                git:
                    commit: c0e746c8035e4285b32a3930124d6b772ec733ab
                    remote: https://github.com/Marco-Yang/DWBC.git
                gpu: NVIDIA GeForce RTX 4090 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 9728
                      memoryTotal: "17171480576"
                      name: NVIDIA GeForce RTX 4090 Laptop GPU
                      uuid: GPU-af0879a4-d638-4d3a-f44e-c4601ed506c2
                host: adam-Alienware-m18-R2
                memory:
                    total: "67091251200"
                os: Linux-6.8.0-87-generic-x86_64-with-glibc2.17
                program: legged_gym/legged_gym/scripts/train.py
                python: CPython 3.8.20
                root: /home/adam/Deep-Whole-Body-Control
                startedAt: "2025-11-27T12:02:18.332845Z"
                writerId: 6wrnqflqh28g5jz6s9on0o2p02xzc0a1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 3
                - 13
                - 61
            "4": 3.8.20
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
