_wandb:
    value:
        cli_version: 0.23.0
        e:
            1qezmtmb3p84ll4xyi6z87va6zx1aiol:
                args:
                    - --task=widowGo1
                    - --run_name=test_run
                    - --exptid=1
                    - --headless
                    - --num_envs=64
                codePath: legged_gym/legged_gym/scripts/train.py
                codePathLocal: legged_gym/legged_gym/scripts/train.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "916243312640"
                        used: "425291403264"
                email: 3155853275@qq.com
                executable: /home/adam/anaconda3/envs/DWBC/bin/python
                git:
                    commit: 8159e4ed8695b2d3f62a40d2ab8d88205ac5021a
                    remote: https://github.com/MarkFzp/Deep-Whole-Body-Control.git
                gpu: NVIDIA GeForce RTX 4090 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 9728
                      memoryTotal: "17171480576"
                      name: NVIDIA GeForce RTX 4090 Laptop GPU
                      uuid: GPU-af0879a4-d638-4d3a-f44e-c4601ed506c2
                host: adam-Alienware-m18-R2
                memory:
                    total: "67091259392"
                os: Linux-6.8.0-87-generic-x86_64-with-glibc2.17
                program: legged_gym/legged_gym/scripts/train.py
                python: CPython 3.8.20
                root: /home/adam/Deep-Whole-Body-Control
                startedAt: "2025-11-26T03:59:07.965602Z"
                writerId: 1qezmtmb3p84ll4xyi6z87va6zx1aiol
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 3
                - 13
            "4": 3.8.20
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
